export const Country = [
  "Seleccion su Pais",
  "Afganistán",
  "Albania",
  "Algeria",
  "Samoa Americana",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antártida",
  "Antigua y Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaiyán",
  "Bahamas",
  "Bahrein",
  "Bangladesh",
  "Barbados",
  "Bielorrusia",
  "Bélgica",
  "Belice",
  "Benín",
  "Bermuda",
  "Bután",
  "Bolivia",
  "Bosnia-Herzegovina",
  "Botswana",
  "Brasil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Camboya",
  "Camerún",
  "Canadá",
  "Cabo Verde",
  "Islas Caimán",
  "República Centroafricana",
  "Chad",
  "Chile",
  "China",
  "Isla de Navidad",
  "Islas Cocos",
  "Colombia",
  "Comores",
  "República del Congo",
  "República Democrática del Congo",
  "Islas Cook",
  "Costa Rica",
  "Costa de Marfíl",
  "Croacia",
  "Cuba",
  "Chipre",
  "República Checa",
  "Dinamarca",
  "Djibouti",
  "Dominica",
  "República Dominicana",
  "Ecuador",
  "Egipto",
  "El Salvador",
  "Guinea Ecuatorial",
  "Eritrea",
  "Estonia",
  "Etiopía",
  "Islas Malvinas",
  "Islas Feroe",
  "Fiji",
  "Finlandia",
  "Francia",
  "Guyana Francesa",
  "Polinesia Francesa",
  "Tierras Australes y Antárticas Francesas",
  "Gabón",
  "Gambia",
  "Georgia",
  "Alemania",
  "Ghana",
  "Gibraltar",
  "Grecia",
  "Groenlandia",
  "Granada",
  "Guadalupe",
  "Guam",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haití",
  "Vaticano",
  "Honduras",
  "Hong Kong",
  "Hungría",
  "Islandia",
  "India",
  "Indonesia",
  "Irán",
  "Iraq",
  "Irlanda",
  "Israel",
  "Italia",
  "Jamaica",
  "Japón",
  "Jordania",
  "Kazajstán",
  "Kenia",
  "Kiribati",
  "Corea del Norte",
  "Corea del Sur",
  "Kuwait",
  "Kirguistán",
  "Laos",
  "Letonia",
  "Líbano",
  "Lesotho",
  "Liberia",
  "Libia",
  "Liechtenstein",
  "Lituania",
  "Luxemburgo",
  "Macao",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malasia",
  "Maldivas",
  "Mali",
  "Malta",
  "Islas Marshall",
  "Martinica",
  "Mauritania",
  "Mauricio",
  "Mayotte",
  "México",
  "Estados Federados de Micronesia",
  "Moldavia",
  "Mónaco",
  "Mongolia",
  "Montserrat",
  "Marruecos",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Holanda",
  "Antillas Holandesas",
  "Nueva Caledonia",
  "Nueva Zelanda",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Islas Norfolk",
  "Islas Marianas del Norte",
  "Noruega",
  "Omán",
  "Pakistán",
  "Palau",
  "Palestina",
  "Panamá",
  "Papua Nueva Guinea",
  "Paraguay",
  "Perú",
  "Filipinas",
  "Pitcairn",
  "Polonia",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunión",
  "Rumanía",
  "Rusia",
  "Ruanda",
  "Santa Helena",
  "San Kitts y Nevis",
  "Santa Lucía",
  "San Vicente y Granadinas",
  "Samoa",
  "San Marino",
  "Santo Tomé y Príncipe",
  "Arabia Saudita",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leona",
  "Singapur",
  "Eslovaquía",
  "Eslovenia",
  "Islas Salomón",
  "Somalia",
  "Sudáfrica",
  "España",
  "Sri Lanka",
  "Sudán",
  "Surinam",
  "Swazilandia",
  "Suecia",
  "Suiza",
  "Siria",
  "Taiwán",
  "Tadjikistan",
  "Tanzania",
  "Tailandia",
  "Timor Oriental",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad y Tobago",
  "Túnez",
  "Turquía",
  "Turkmenistan",
  "Islas Turcas y Caicos",
  "Tuvalu",
  "Uganda",
  "Ucrania",
  "Emiratos Árabes Unidos",
  "Reino Unido",
  "Estados Unidos",
  "Uruguay",
  "Uzbekistán",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Islas Vírgenes Británicas",
  "Islas Vírgenes Americanas",
  "Wallis y Futuna",
  "Sáhara Occidental",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
